In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt

plt.rc('font', family='AppleGothic')
plt.rcParams['axes.unicode_minus'] = False

# Using TensorFlow like NumPy
텐서는 넘파이와 매우 비슷하다. 즉 텐서는 다차원 배열이다. 하지만 스칼라 값도 가질 수 있다.

## 1. 텐서와 연산
tf.constant() 함수로 텐서를 만들 수 있다.<br>
⬇︎ 

In [2]:
t = tf.constant([[1.,2.,3.],[4.,5.,6.]])
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [5]:
print(t.shape, t.dtype)

(2, 3) <dtype: 'float32'>


In [11]:
t[:,1]
t[:2,:2]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [4., 5.]], dtype=float32)>

In [15]:
# 연산
t+10
tf.add(t,10) # 위의 연산과 같은 결과

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [16]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [17]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [18]:
tf.transpose(t)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

tf.transpose(t)라고 써야 한다. 넘파이 처럼 t.T라고 쓰면 안된다. 그 이유는 tf.transpose() 함수가 넘파이 T 속성과 완전히 동일한 작업을 수행하지 않기 때문이다. <br>
- 텐서플로에서는 전치된 데이터의 복사본으로 새로운 텐서가 만들어지지만 넘파이에서 t.T는 동일한 데이터의 전치된 view일 뿐이다.
- 비슷하게 tf.reduce_sum() 연산으로 이름 지은 것은 이 GPU 커널이 원소가 추가된 순서를 보장하지 않는 reduce 알고리즘을 사용하기 때문이다.

## 2. 텐서와 넘파이
넘파이 배열로 텐서를 만들 수 있고 그 반대도 가능하다. 또한 넘파이 배열에 텐서플로 연산을 할 수 있고 그 반대도 가능하다.

In [20]:
import numpy as np

a = np.array([2., 4., 5.])
tf.constant(a) # tf

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [25]:
t.numpy()
np.array(t) # 위 코드와 같은 결과

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [27]:
tf.square(a) # tf
np.square(t) # np

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

## 3. 타입 변환
텐서플로는 어떤 타입 변환도 자동으로 수행하지 않는다. 
- 실수 텐서와 정수 텐서는 더할 수 없다.
- 32비트 실수와 64비트 실수도 더할 수 없다.

In [32]:
# float + int 불가능
# tf.constant(2.) + tf.constant(4) 
# 32bit float + 64bit float 불가능
# tf.constant(2.) + tf.constant(2., dtype=tf.float64)

## 4. 변수
위의 tf.Tensor는 변경이 불가능한 객체이다. 따라서 일반적인 텐서로는 역전파로 변경되어야 하는 신경망의 가중치를 구할 수 없다. 때문에 tf.Variable이 필요하다.
- assign() 메서드를 이용하여 변숫값을 바꿀 수 있다.<br>
흠,,근데 v[0, 1].assign(42) 연산이 안된다...?

In [33]:
v = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [34]:
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [46]:
v.scatter_nd_update(
    indices=[[0, 0], [1, 2]], updates=[100., 200.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,   4.,   6.],
       [  8.,  10., 200.]], dtype=float32)>

In [49]:
v.scatter_nd_update(
   indices=[[0,1]], updates=[500])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100., 500.,   6.],
       [  8.,  10., 200.]], dtype=float32)>

In [56]:
sparse_delta = tf.IndexedSlices(values=[[1., 2., 3.], [4., 5., 6.]],
                                indices=[1, 0])
print(sparse_delta)
v.scatter_update(sparse_delta)

IndexedSlices(indices=[1, 0], values=[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])


<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[4., 5., 6.],
       [1., 2., 3.]], dtype=float32)>

In [57]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[4., 5., 6.],
       [1., 2., 3.]], dtype=float32)>

<class 'tensorflow.python.framework.sparse_tensor.SparseTensor'>
